name: Ultima versao
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: mensagem
        run: echo "Alguem fez um push!"

